CREATE TABLE  "LOGIN" 
   (	"REGISTRO" NUMBER(8,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(200) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200) NOT NULL ENABLE, 
	"IDADE" NUMBER(5,0), 
	"PROFISSAO" VARCHAR2(200), 
	 CONSTRAINT "LOGIN_PK" PRIMARY KEY ("REGISTRO")
  USING INDEX  ENABLE
   )
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_LOGIN" 
  before insert on "LOGIN"               
  for each row  
begin   
  if :NEW."REGISTRO" is null then 
    select "LOGIN_SEQ".nextval into :NEW."REGISTRO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_LOGIN" ENABLE
/
